#include "../include/../include/mlir_emitter.h"
#include <sstream>
#include <stdexcept>



namespace nnc {

// ---- Вспомогательные статические методы ----
std::string MLIREmitter::ind(int n) {
    return std::string(n * 2, ' ');
}

// Заменяем символы, запрещённые в MLIR-идентификаторах
static std::string sanitize(const std::string& s) {
    std::string r;
    r.reserve(s.size());
    for (char c : s) {
        if (std::isalnum(c) || c == '_') r += c;
        else                              r += '_';
    }
    return r;
}

std::string MLIREmitter::ssaName(const std::string& name) {
    return "%" + sanitize(name);
}

std::string MLIREmitter::mlirScalarType(DType dt) {
    switch (dt) {
        case DType::Float32: return "f32";
        case DType::Float64: return "f64";
        case DType::Int32:   return "i32";
        case DType::Int64:   return "i64";
        default:             return "f32";  // по умолчанию - float
    }
}

std::string MLIREmitter::mlirTensorType(const TensorInfo& t) {
    // Строим тип: tensor<d0xd1x…xf32>
    // Динамические измерения представляются символом '?'
    std::string dims;
    for (int64_t d : t.shape.dims) {
        dims += (d < 0 ? "?" : std::to_string(d));
        dims += "x";
    }
    return "tensor<" + dims + mlirScalarType(t.dtype) + ">";
}

// ---- Конструктор ---
MLIREmitter::MLIREmitter(const MLIREmitOptions& opts) : opts_(opts) {}

// ---- Главный метод ----
std::string MLIREmitter::emitToString(const Graph& graph) const {
    std::ostringstream oss;
    emit(graph, oss);
    return oss.str();
}

void MLIREmitter::emit(const Graph& graph, std::ostream& os) const {
    // ---- Шапка ----
    os << "// Auto-generated by nnc-codegen\n";
    os << "// Graph: " << graph.name << "\n\n";

    if (opts_.emitModuleWrapper)
        os << "module {\n\n";

    // ---- Сигнатура функции ----
    // Аргументы - входные тензоры графа (без инициализаторов)
    os << ind(1) << "func.func @" << opts_.funcName << "(";

    bool firstArg = true;
    for (const auto& inpName : graph.inputs) {
        const TensorInfo* t = graph.getTensor(inpName);
        if (!t || t->isInitializer) continue;  // пропускаем веса
        if (!firstArg) os << ", ";
        os << ssaName(inpName) << ": ";
        os << (t ? mlirTensorType(*t) : "tensor<*xf32>");
        firstArg = false;
    }
    os << ") -> (";

    // Возвращаемые типы
    bool firstOut = true;
    for (const auto& outName : graph.outputs) {
        const TensorInfo* t = graph.getTensor(outName);
        if (!firstOut) os << ", ";
        os << (t ? mlirTensorType(*t) : "tensor<*xf32>");
        firstOut = false;
    }
    os << ") {\n\n";

    // ---- Тело функции: объявляем инициализаторы ----
    for (const auto& [name, t] : graph.tensors) {
        if (!t.isInitializer || t.floatData.empty()) continue;

        // Пример: объявляем скаляр или 1-d константу
        // Полная сериализация тензорных констант - за рамками задания,
        // здесь показываем как встроить dense-атрибут для небольших весов
        os << ind(2) << "// initializer: " << name << "\n";
        os << ind(2) << ssaName(name) << " = arith.constant ";
        os << "dense<[";
        for (size_t i = 0; i < t.floatData.size(); ++i) {
            if (i) os << ", ";
            os << t.floatData[i];
        }
        os << "]> : " << mlirTensorType(t) << "\n\n";
    }

    // ---- Тело функции: операции ----
    for (const auto& node : graph.nodes) {
        if (opts_.emitNodeComments)
            os << ind(2) << "// ONNX node: " << node.name
               << " [" << opTypeToString(node.opType) << "]\n";

        switch (node.opType) {
            case OpType::Add:    emitAdd   (node, graph, os, 2); break;
            case OpType::Mul:    emitMul   (node, graph, os, 2); break;
            case OpType::Conv:   emitConv  (node, graph, os, 2); break;
            case OpType::Relu:   emitRelu  (node, graph, os, 2); break;
            case OpType::MatMul: emitMatMul(node, graph, os, 2); break;
            case OpType::Gemm:   emitGemm  (node, graph, os, 2); break;
            default:
                os << ind(2) << "// WARNING: unsupported op '"
                   << opTypeToString(node.opType) << "' — skipped\n";
        }
        os << "\n";
    }

    // ---- return ----
    os << ind(2) << "return ";
    for (size_t i = 0; i < graph.outputs.size(); ++i) {
        if (i) os << ", ";
        os << ssaName(graph.outputs[i]);
    }
    // Тип возвращаемого значения
    os << " : ";
    for (size_t i = 0; i < graph.outputs.size(); ++i) {
        if (i) os << ", ";
        const TensorInfo* t = graph.getTensor(graph.outputs[i]);
        os << (t ? mlirTensorType(*t) : "tensor<*xf32>");
    }
    os << "\n";

    os << ind(1) << "}\n";
    if (opts_.emitModuleWrapper)
        os << "\n} // module\n";
}

// ---- Генераторы отдельных операций ----

// Поэлементное сложение через linalg.map или tensor операции
void MLIREmitter::emitAdd(const Node& node, const Graph& g,
                          std::ostream& os, int indent) const {
    // %out = linalg.add ins(%a, %b) outs(%dst)
    // Упрощённо: используем tensor dialect
    const TensorInfo* outT = g.getTensor(node.outputs[0]);
    std::string outType = outT ? mlirTensorType(*outT) : "tensor<*xf32>";

    os << ind(indent) << ssaName(node.outputs[0]) << " = linalg.add\n";
    os << ind(indent+1) << "ins("
       << ssaName(node.inputs[0]) << ", "
       << ssaName(node.inputs[1]) << " : "
       << outType << ", " << outType << ")\n";
    os << ind(indent+1) << "outs("
       << ssaName(node.outputs[0]) << "_buf : " << outType << ")\n";
    os << ind(indent) << "  -> " << outType << "\n";
}

void MLIREmitter::emitMul(const Node& node, const Graph& g,
                          std::ostream& os, int indent) const {
    const TensorInfo* outT = g.getTensor(node.outputs[0]);
    std::string outType = outT ? mlirTensorType(*outT) : "tensor<*xf32>";

    os << ind(indent) << ssaName(node.outputs[0]) << " = linalg.mul\n";
    os << ind(indent+1) << "ins("
       << ssaName(node.inputs[0]) << ", "
       << ssaName(node.inputs[1]) << " : "
       << outType << ", " << outType << ")\n";
    os << ind(indent+1) << "outs("
       << ssaName(node.outputs[0]) << "_buf : " << outType << ")\n";
    os << ind(indent) << "  -> " << outType << "\n";
}

// Conv: linalg.conv_2d_nchw_fchw (стандартная 2D свёртка NCHW)
void MLIREmitter::emitConv(const Node& node, const Graph& g,
                           std::ostream& os, int indent) const {
    const ConvAttrs* ca = std::get_if<ConvAttrs>(&node.attrs);

    const TensorInfo* input  = g.getTensor(node.inputs[0]);  // X
    const TensorInfo* filter = g.getTensor(node.inputs[1]);  // W
    const TensorInfo* outT   = g.getTensor(node.outputs[0]);

    std::string inType     = input  ? mlirTensorType(*input)  : "tensor<*xf32>";
    std::string filterType = filter ? mlirTensorType(*filter) : "tensor<*xf32>";
    std::string outType    = outT   ? mlirTensorType(*outT)   : "tensor<*xf32>";

    // Атрибуты dilations и strides передаются как dense-атрибуты
    auto vecToAttr = [](const std::vector<int64_t>& v, int64_t def) -> std::string {
        if (v.empty()) return "dense<" + std::to_string(def) + "> : vector<2xi64>";
        std::string s = "dense<[";
        for (size_t i = 0; i < v.size(); ++i) { if (i) s += ", "; s += std::to_string(v[i]); }
        return s + "]> : vector<2xi64>";
    };

    std::string dilStr = ca ? vecToAttr(ca->dilations, 1) : "dense<1> : vector<2xi64>";
    std::string strStr = ca ? vecToAttr(ca->strides,   1) : "dense<1> : vector<2xi64>";

    os << ind(indent) << ssaName(node.outputs[0])
       << " = linalg.conv_2d_nchw_fchw\n";
    os << ind(indent+1) << "{ dilations = " << dilStr
       << ", strides = " << strStr << " }\n";
    os << ind(indent+1) << "ins(" << ssaName(node.inputs[0])
       << ", " << ssaName(node.inputs[1])
       << " : " << inType << ", " << filterType << ")\n";
    os << ind(indent+1) << "outs(" << ssaName(node.outputs[0])
       << "_init : " << outType << ")\n";
    os << ind(indent) << "  -> " << outType << "\n";
}

// Relu: linalg.elemwise_unary или просто tosa.clamp(min=0)
// Используем linalg.generic с arith.maxf(x, 0)
void MLIREmitter::emitRelu(const Node& node, const Graph& g,
                           std::ostream& os, int indent) const {
    const TensorInfo* inT  = g.getTensor(node.inputs[0]);
    std::string tensorType = inT ? mlirTensorType(*inT) : "tensor<*xf32>";

    os << ind(indent) << ssaName(node.outputs[0])
       << " = linalg.generic\n";
    os << ind(indent+1) << "{ indexing_maps = [affine_map<(d0) -> (d0)>,\n";
    os << ind(indent+1) << "                  affine_map<(d0) -> (d0)>],\n";
    os << ind(indent+1) << "  iterator_types = [\"parallel\"] }\n";
    os << ind(indent+1) << "ins(" << ssaName(node.inputs[0])
       << " : " << tensorType << ")\n";
    os << ind(indent+1) << "outs(" << ssaName(node.outputs[0])
       << "_buf : " << tensorType << ") {\n";
    os << ind(indent+2) << "^bb0(%in: f32, %out: f32):\n";
    os << ind(indent+3) << "%zero = arith.constant 0.0 : f32\n";
    os << ind(indent+3) << "%res  = arith.maxf %in, %zero : f32\n";
    os << ind(indent+3) << "linalg.yield %res : f32\n";
    os << ind(indent+1) << "} -> " << tensorType << "\n";
}

// MatMul: linalg.matmul (2D × 2D)
void MLIREmitter::emitMatMul(const Node& node, const Graph& g,
                              std::ostream& os, int indent) const {
    const TensorInfo* aT   = g.getTensor(node.inputs[0]);
    const TensorInfo* bT   = g.getTensor(node.inputs[1]);
    const TensorInfo* outT = g.getTensor(node.outputs[0]);

    std::string typeA   = aT   ? mlirTensorType(*aT)   : "tensor<?x?xf32>";
    std::string typeB   = bT   ? mlirTensorType(*bT)   : "tensor<?x?xf32>";
    std::string typeOut = outT ? mlirTensorType(*outT)  : "tensor<?x?xf32>";

    os << ind(indent) << ssaName(node.outputs[0])
       << " = linalg.matmul\n";
    os << ind(indent+1) << "ins(" << ssaName(node.inputs[0])
       << ", " << ssaName(node.inputs[1])
       << " : " << typeA << ", " << typeB << ")\n";
    os << ind(indent+1) << "outs(" << ssaName(node.outputs[0])
       << "_init : " << typeOut << ")\n";
    os << ind(indent) << "  -> " << typeOut << "\n";
}

void MLIREmitter::emitGemm(const Node& node, const Graph& g,
                            std::ostream& os, int indent) const {
    const GemmAttrs* ga = std::get_if<GemmAttrs>(&node.attrs);

    const TensorInfo* aT   = g.getTensor(node.inputs[0]);
    const TensorInfo* bT   = g.getTensor(node.inputs[1]);
    const TensorInfo* outT = g.getTensor(node.outputs[0]);

    std::string typeA   = aT   ? mlirTensorType(*aT)   : "tensor<?x?xf32>";
    std::string typeB   = bT   ? mlirTensorType(*bT)   : "tensor<?x?xf32>";
    std::string typeOut = outT ? mlirTensorType(*outT)  : "tensor<?x?xf32>";

    float alpha = ga ? ga->alpha : 1.0f;
    float beta  = ga ? ga->beta  : 1.0f;

    os << ind(indent) << "// Gemm: alpha=" << alpha << ", beta=" << beta << "\n";

    // Шаг 1: matmul (A × B)
    std::string tmpName = ssaName(node.outputs[0]) + "_mm";
    os << ind(indent) << tmpName << " = linalg.matmul\n";
    os << ind(indent+1) << "ins(" << ssaName(node.inputs[0])
       << ", " << ssaName(node.inputs[1])
       << " : " << typeA << ", " << typeB << ")\n";
    os << ind(indent+1) << "outs(" << ssaName(node.outputs[0])
       << "_init : " << typeOut << ")\n";
    os << ind(indent) << "  -> " << typeOut << "\n\n";

    // Шаг 2: если есть смещение C (bias), добавляем linalg.add
    if (node.inputs.size() >= 3) {
        os << ind(indent) << ssaName(node.outputs[0])
           << " = linalg.add\n";
        os << ind(indent+1) << "ins(" << tmpName << ", "
           << ssaName(node.inputs[2])
           << " : " << typeOut << ", " << typeOut << ")\n";
        os << ind(indent+1) << "outs(" << ssaName(node.outputs[0])
           << "_buf : " << typeOut << ")\n";
        os << ind(indent) << "  -> " << typeOut << "\n";
    } else {
        os << ind(indent) << ssaName(node.outputs[0])
           << " = " << tmpName << "\n";
    }
}

}
